using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net.Mime;
using System.Threading;
using System.Threading.Tasks;
using Jellyfin.Plugin.JellyfinHelper.Configuration;
using Jellyfin.Plugin.JellyfinHelper.Services.Common;
using Jellyfin.Plugin.JellyfinHelper.Services.ConfigAccess;
using Jellyfin.Plugin.JellyfinHelper.Services.Recommendation;
using Jellyfin.Plugin.JellyfinHelper.Services.Recommendation.WatchHistory;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Jellyfin.Plugin.JellyfinHelper.Api;

/// <summary>
///     API controller for smart recommendations and watch history. Serves cached recommendation data generated by the scheduled task, with an option to fetch watch profiles on demand.
/// </summary>
[ApiController]
[Authorize(Policy = "RequiresElevation")]
[Route("JellyfinHelper/Recommendations")]
[Produces(MediaTypeNames.Application.Json)]
[ProducesResponseType(StatusCodes.Status401Unauthorized)]
[ProducesResponseType(StatusCodes.Status403Forbidden)]
public class RecommendationController : ControllerBase
{
    private const string RecommendationsDisabledMessage = "Smart Recommendations are disabled in plugin configuration.";

    private readonly IRecommendationCacheService _cacheService;
    private readonly IPluginConfigurationService _configService;
    private readonly IRecommendationEngine _engine;
    private readonly IWatchHistoryService _watchHistoryService;

    private static readonly SemaphoreSlim CacheFillLock = new(1, 1);

    /// <summary>
    ///     Initializes a new instance of the <see cref="RecommendationController" /> class.
    /// </summary>
    /// <param name="engine">The recommendation engine.</param>
    /// <param name="cacheService">The recommendation cache service.</param>
    /// <param name="watchHistoryService">The watch history service.</param>
    /// <param name="configService">The plugin configuration service.</param>
    public RecommendationController(
        IRecommendationEngine engine,
        IRecommendationCacheService cacheService,
        IWatchHistoryService watchHistoryService,
        IPluginConfigurationService configService)
    {
        _engine = engine;
        _cacheService = cacheService;
        _watchHistoryService = watchHistoryService;
        _configService = configService;
    }

    /// <summary>
    ///     Gets cached recommendations for all users (admin overview). Returns the latest cached results from the scheduled task.
    /// </summary>
    /// <param name="maxPerUser">Maximum recommendations per user (default: from config, max: 100).</param>
    /// <param name="cancellationToken">Token to cancel the request.</param>
    /// <returns>A list of recommendation results, one per user.</returns>
    [HttpGet]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status503ServiceUnavailable)]
    public async Task<ActionResult<List<RecommendationResult>>> GetAllRecommendations(
        [FromQuery] int maxPerUser = 0,
        CancellationToken cancellationToken = default)
    {
        var config = _configService.GetConfiguration();
        if (config.RecommendationsTaskMode == TaskMode.Deactivate)
        {
            return StatusCode(
                StatusCodes.Status503ServiceUnavailable,
                RecommendationsDisabledMessage);
        }

        var configuredMax = Math.Clamp(config.MaxRecommendationsPerUser, 1, 100);
        // Use config default if not specified via query parameter; used only for trimming the response
        var requestedMax = Math.Clamp(maxPerUser <= 0 ? configuredMax : maxPerUser, 1, 100);

        var cached = _cacheService.LoadResults();
        if (cached is not null)
        {
            // Apply requested limit to cached results
            var trimmed = TrimRecommendations(cached, requestedMax);
            return Ok(trimmed);
        }

        // No cache - acquire lock so only one caller generates at a time (double-check inside).
        var acquired = false;
        try
        {
            await CacheFillLock.WaitAsync(cancellationToken).ConfigureAwait(false);
            acquired = true;

            // Re-check under lock: another waiter may have filled the cache while we waited.
            cached = _cacheService.LoadResults();
            if (cached is not null)
            {
                return Ok(TrimRecommendations(cached, requestedMax));
            }

            // Generate at the configured max so the cache is not under-filled
            var results = _engine.GetAllRecommendations(configuredMax, cancellationToken);

            // Only persist to disk when TaskMode is Activate (not DryRun).
            // DryRun results are cached in the browser by the UI JavaScript.
            if (config.RecommendationsTaskMode == TaskMode.Activate)
            {
                _cacheService.SaveResults(results);
            }

            return Ok(TrimRecommendations(results, requestedMax));
        }
        finally
        {
            if (acquired)
            {
                CacheFillLock.Release();
            }
        }
    }

    /// <summary>
    ///     Gets a read-only snapshot of the ensemble scoring strategy's live internal state (alpha, neural beta,
    ///     quality-gate freeze, sigmoid midpoint, trend, and training counts) for operator diagnostics. Pure read:
    ///     it never generates recommendations or fills the cache.
    /// </summary>
    /// <param name="userId">
    ///     Optional user id. When supplied (and non-empty), returns that user's per-user model state (or the
    ///     global model as cold-start fallback, flagged via <see cref="EnsembleDiagnosticsResponse.IsPerUser"/>).
    ///     When omitted, returns the shared global model state.
    /// </param>
    /// <returns>The ensemble diagnostics, or a response with <see cref="EnsembleDiagnosticsResponse.Available"/> set to false when the active strategy is not an ensemble or no state exists yet.</returns>
    [HttpGet("Diagnostics/Ensemble")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status503ServiceUnavailable)]
    public ActionResult<EnsembleDiagnosticsResponse> GetEnsembleDiagnostics([FromQuery] Guid? userId = null)
    {
        if (_configService.GetConfiguration().RecommendationsTaskMode == TaskMode.Deactivate)
        {
            return StatusCode(
                StatusCodes.Status503ServiceUnavailable,
                RecommendationsDisabledMessage);
        }

        if (userId is not { } id || id == Guid.Empty)
        {
            var globalDiagnostics = _engine.GetEnsembleDiagnostics();
            return globalDiagnostics is null
                ? Ok(new EnsembleDiagnosticsResponse { Available = false })
                : Ok(EnsembleDiagnosticsResponse.FromDiagnostics(globalDiagnostics));
        }

        var (diagnostics, isPerUser) = _engine.GetUserEnsembleDiagnostics(id);
        if (diagnostics is null)
        {
            return Ok(new EnsembleDiagnosticsResponse { Available = false });
        }

        // The per-user flag comes from the same resolution as the snapshot, so a cold-start user on the
        // global model is never mislabelled as having an individual model. The name is a display-only extra:
        // GetUserWatchProfile builds the profile without the per-user isolation GetAllUserWatchProfiles has, so
        // a transient build failure must not turn valid diagnostics into a 500. Fall back to a null name.
        string? userName = null;
        try
        {
            userName = _watchHistoryService.GetUserWatchProfile(id)?.UserName;
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch (Exception ex) when (!ex.IsFatal())
        {
            // The name is a display-only nicety and null is already a valid, handled value, so a failed lookup
            // is swallowed rather than logged: it is neither actionable nor worth a controller-level logger.
        }

        return Ok(EnsembleDiagnosticsResponse.FromDiagnostics(diagnostics, isPerUser, userName));
    }

    /// <summary>
    ///     Gets recommendations for a specific user.
    /// </summary>
    /// <param name="userId">The Jellyfin user ID.</param>
    /// <param name="maxResults">Maximum number of recommendations (default: from config, max: 100).</param>
    /// <param name="cancellationToken">Token to cancel the request.</param>
    /// <returns>The recommendation result for the user.</returns>
    [HttpGet("{userId}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(string), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status503ServiceUnavailable)]
    public ActionResult<RecommendationResult> GetUserRecommendations(
        Guid userId,
        [FromQuery] int maxResults = 0,
        CancellationToken cancellationToken = default)
    {
        var config = _configService.GetConfiguration();
        if (config.RecommendationsTaskMode == TaskMode.Deactivate)
        {
            return StatusCode(
                StatusCodes.Status503ServiceUnavailable,
                RecommendationsDisabledMessage);
        }

        if (userId == Guid.Empty)
        {
            return BadRequest("A valid, non-empty userId is required.");
        }

        maxResults = Math.Clamp(maxResults <= 0 ? config.MaxRecommendationsPerUser : maxResults, 1, 100);

        // Try cache first - return a copy to avoid mutating the cached object
        var cached = _cacheService.LoadResults();
        var cachedUser = cached?.FirstOrDefault(r => r.UserId == userId);
        if (cachedUser is not null)
        {
            if (cachedUser.Recommendations.Count <= maxResults)
            {
                return Ok(cachedUser);
            }

            // Return a trimmed copy without mutating the cache
            var copy = new RecommendationResult
            {
                UserId = cachedUser.UserId,
                UserName = cachedUser.UserName,
                Profile = cachedUser.Profile,
                ScoringStrategy = cachedUser.ScoringStrategy,
                ScoringStrategyKey = cachedUser.ScoringStrategyKey,
                GeneratedAt = cachedUser.GeneratedAt,
                Cohort = cachedUser.Cohort,
                Recommendations = new Collection<RecommendedItem>(
                    cachedUser.Recommendations.Take(maxResults).ToList())
            };
            return Ok(copy);
        }

        // Generate on demand
        var result = _engine.GetRecommendations(userId, maxResults, cancellationToken);
        if (result is null)
        {
            return NotFound();
        }

        return Ok(result);
    }

    /// <summary>
    ///     Gets the watch profile for a specific user (detailed watch history stats).
    /// </summary>
    /// <param name="userId">The Jellyfin user ID.</param>
    /// <returns>The user's watch profile.</returns>
    [HttpGet("WatchProfile/{userId}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(string), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status503ServiceUnavailable)]
    public ActionResult<UserWatchProfile> GetUserWatchProfile(Guid userId)
    {
        if (_configService.GetConfiguration().RecommendationsTaskMode == TaskMode.Deactivate)
        {
            return StatusCode(
                StatusCodes.Status503ServiceUnavailable,
                RecommendationsDisabledMessage);
        }

        if (userId == Guid.Empty)
        {
            return BadRequest("A valid, non-empty userId is required.");
        }

        var profile = _watchHistoryService.GetUserWatchProfile(userId);
        if (profile is null)
        {
            return NotFound();
        }

        return Ok(profile);
    }

    /// <summary>
    ///     Gets watch profiles for all users (admin overview).
    /// </summary>
    /// <returns>A list of watch profiles, one per user.</returns>
    [HttpGet("WatchProfiles")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status503ServiceUnavailable)]
    public ActionResult<List<UserWatchProfile>> GetAllWatchProfiles()
    {
        if (_configService.GetConfiguration().RecommendationsTaskMode == TaskMode.Deactivate)
        {
            return StatusCode(
                StatusCodes.Status503ServiceUnavailable,
                RecommendationsDisabledMessage);
        }

        var profiles = _watchHistoryService.GetAllUserWatchProfiles();

        // Return lean copies without the full watched items list (never mutate originals)
        var lean = profiles.Select(p => new UserWatchProfile
        {
            UserId = p.UserId,
            UserName = p.UserName,
            WatchedMovieCount = p.WatchedMovieCount,
            WatchedEpisodeCount = p.WatchedEpisodeCount,
            WatchedSeriesCount = p.WatchedSeriesCount,
            TotalWatchTimeTicks = p.TotalWatchTimeTicks,
            LastActivityDate = p.LastActivityDate,
            GenreDistribution = p.GenreDistribution,
            FavoriteCount = p.FavoriteCount,
            AverageCommunityRating = p.AverageCommunityRating,
            WatchedItems = []
        }).ToList();

        return Ok(lean);
    }

    /// <summary>
    ///     Creates a trimmed copy of each user's recommendation list without mutating the cache.
    /// </summary>
    /// <param name="results">The full recommendation results (not modified).</param>
    /// <param name="maxPerUser">Maximum recommendations per user.</param>
    /// <returns>A new collection with trimmed recommendation counts.</returns>
    private static IReadOnlyList<RecommendationResult> TrimRecommendations(
        IReadOnlyList<RecommendationResult> results,
        int maxPerUser)
    {
        var needsTrim = results.Any(r => r.Recommendations.Count > maxPerUser);
        if (!needsTrim)
        {
            return results;
        }

        var trimmed = new List<RecommendationResult>();
        foreach (var r in results)
        {
            if (r.Recommendations.Count > maxPerUser)
            {
                trimmed.Add(
                    new RecommendationResult
                    {
                        UserId = r.UserId,
                        UserName = r.UserName,
                        Profile = r.Profile,
                        ScoringStrategy = r.ScoringStrategy,
                        ScoringStrategyKey = r.ScoringStrategyKey,
                        GeneratedAt = r.GeneratedAt,
                        Cohort = r.Cohort,
                        Recommendations = new Collection<RecommendedItem>(
                            r.Recommendations.Take(maxPerUser).ToList())
                    });
            }
            else
            {
                trimmed.Add(r);
            }
        }

        return trimmed;
    }
}