using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net.Mime;
using System.Threading;
using Jellyfin.Plugin.JellyfinHelper.Configuration;
using Jellyfin.Plugin.JellyfinHelper.Services.ConfigAccess;
using Jellyfin.Plugin.JellyfinHelper.Services.Recommendation;
using Jellyfin.Plugin.JellyfinHelper.Services.Recommendation.WatchHistory;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Jellyfin.Plugin.JellyfinHelper.Api;

/// <summary>
///     API controller for smart recommendations and watch history.
///     Serves cached recommendation data generated by the scheduled task,
///     with an option to fetch watch profiles on demand.
/// </summary>
[ApiController]
[Authorize(Policy = "RequiresElevation")]
[Route("JellyfinHelper/Recommendations")]
[Produces(MediaTypeNames.Application.Json)]
public class RecommendationController : ControllerBase
{
    private readonly IRecommendationCacheService _cacheService;
    private readonly IPluginConfigurationService _configService;
    private readonly IRecommendationEngine _engine;
    private readonly IWatchHistoryService _watchHistoryService;

    /// <summary>
    ///     Initializes a new instance of the <see cref="RecommendationController" /> class.
    /// </summary>
    /// <param name="engine">The recommendation engine.</param>
    /// <param name="cacheService">The recommendation cache service.</param>
    /// <param name="watchHistoryService">The watch history service.</param>
    /// <param name="configService">The plugin configuration service.</param>
    public RecommendationController(
        IRecommendationEngine engine,
        IRecommendationCacheService cacheService,
        IWatchHistoryService watchHistoryService,
        IPluginConfigurationService configService)
    {
        _engine = engine;
        _cacheService = cacheService;
        _watchHistoryService = watchHistoryService;
        _configService = configService;
    }

    /// <summary>
    ///     Gets cached recommendations for all users (admin overview).
    ///     Returns the latest cached results from the scheduled task.
    ///     If no cache exists and TaskMode is Activate, generates fresh recommendations.
    ///     DryRun mode on-demand generation does NOT persist results.
    /// </summary>
    /// <param name="maxPerUser">Maximum recommendations per user (default: from config, max: 100).</param>
    /// <param name="cancellationToken">Token to cancel the request.</param>
    /// <returns>A list of recommendation results, one per user.</returns>
    [HttpGet]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status503ServiceUnavailable)]
    public ActionResult<List<RecommendationResult>> GetAllRecommendations(
        [FromQuery] int maxPerUser = 0,
        CancellationToken cancellationToken = default)
    {
        if (!IsRecommendationsEnabled())
        {
            return StatusCode(StatusCodes.Status503ServiceUnavailable, "Smart Recommendations are disabled in plugin configuration.");
        }

        var config = _configService.GetConfiguration();
        // Use config default if not specified via query parameter
        if (maxPerUser <= 0)
        {
            maxPerUser = Math.Clamp(config.MaxRecommendationsPerUser, 1, 100);
        }
        else
        {
            maxPerUser = Math.Clamp(maxPerUser, 1, 100);
        }

        var cached = _cacheService.LoadResults();
        if (cached is not null)
        {
            // Apply maxPerUser limit to cached results as well
            var trimmed = TrimRecommendations(cached, maxPerUser);
            return Ok(trimmed);
        }

        // No cache available — generate on demand
        var results = _engine.GetAllRecommendations(maxPerUser, cancellationToken);

        // Only persist to cache when TaskMode is Activate (not DryRun)
        if (config.RecommendationsTaskMode == TaskMode.Activate)
        {
            _cacheService.SaveResults(results);
        }

        return Ok(results);
    }

    /// <summary>
    ///     Gets recommendations for a specific user.
    /// </summary>
    /// <param name="userId">The Jellyfin user ID.</param>
    /// <param name="maxResults">Maximum number of recommendations (default: from config, max: 100).</param>
    /// <param name="cancellationToken">Token to cancel the request.</param>
    /// <returns>The recommendation result for the user.</returns>
    [HttpGet("{userId}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status503ServiceUnavailable)]
    public ActionResult<RecommendationResult> GetUserRecommendations(
        Guid userId,
        [FromQuery] int maxResults = 0,
        CancellationToken cancellationToken = default)
    {
        if (!IsRecommendationsEnabled())
        {
            return StatusCode(StatusCodes.Status503ServiceUnavailable, "Smart Recommendations are disabled in plugin configuration.");
        }

        if (userId == Guid.Empty)
        {
            return BadRequest("A valid, non-empty userId is required.");
        }

        var config = _configService.GetConfiguration();
        if (maxResults <= 0)
        {
            maxResults = Math.Clamp(config.MaxRecommendationsPerUser, 1, 100);
        }
        else
        {
            maxResults = Math.Clamp(maxResults, 1, 100);
        }

        // Try cache first — return a copy to avoid mutating the cached object
        var cached = _cacheService.LoadResults();
        var cachedUser = cached?.FirstOrDefault(r => r.UserId == userId);
        if (cachedUser is not null)
        {
            if (cachedUser.Recommendations.Count <= maxResults)
            {
                return Ok(cachedUser);
            }

            // Return a trimmed copy without mutating the cache
            var copy = new RecommendationResult
            {
                UserId = cachedUser.UserId,
                UserName = cachedUser.UserName,
                Profile = cachedUser.Profile,
                ScoringStrategy = cachedUser.ScoringStrategy,
                ScoringStrategyKey = cachedUser.ScoringStrategyKey,
                GeneratedAt = cachedUser.GeneratedAt,
                Recommendations = new Collection<RecommendedItem>(
                    cachedUser.Recommendations.Take(maxResults).ToList())
            };
            return Ok(copy);
        }

        // Generate on demand
        var result = _engine.GetRecommendations(userId, maxResults, cancellationToken);
        if (result is null)
        {
            return NotFound();
        }

        return Ok(result);
    }

    /// <summary>
    ///     Gets the watch profile for a specific user (detailed watch history stats).
    /// </summary>
    /// <param name="userId">The Jellyfin user ID.</param>
    /// <returns>The user's watch profile.</returns>
    [HttpGet("WatchProfile/{userId}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status503ServiceUnavailable)]
    public ActionResult<UserWatchProfile> GetUserWatchProfile(Guid userId)
    {
        if (!IsRecommendationsEnabled())
        {
            return StatusCode(StatusCodes.Status503ServiceUnavailable, "Smart Recommendations are disabled in plugin configuration.");
        }

        if (userId == Guid.Empty)
        {
            return BadRequest("A valid, non-empty userId is required.");
        }

        var profile = _watchHistoryService.GetUserWatchProfile(userId);
        if (profile is null)
        {
            return NotFound();
        }

        return Ok(profile);
    }

    /// <summary>
    ///     Gets watch profiles for all users (admin overview).
    /// </summary>
    /// <returns>A list of watch profiles, one per user.</returns>
    [HttpGet("WatchProfiles")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status503ServiceUnavailable)]
    public ActionResult<List<UserWatchProfile>> GetAllWatchProfiles()
    {
        if (!IsRecommendationsEnabled())
        {
            return StatusCode(StatusCodes.Status503ServiceUnavailable, "Smart Recommendations are disabled in plugin configuration.");
        }

        var profiles = _watchHistoryService.GetAllUserWatchProfiles();

        // Return lean copies without the full watched items list (never mutate originals)
        var lean = profiles.Select(p => new UserWatchProfile
        {
            UserId = p.UserId,
            UserName = p.UserName,
            WatchedMovieCount = p.WatchedMovieCount,
            WatchedEpisodeCount = p.WatchedEpisodeCount,
            WatchedSeriesCount = p.WatchedSeriesCount,
            TotalWatchTimeTicks = p.TotalWatchTimeTicks,
            LastActivityDate = p.LastActivityDate,
            GenreDistribution = p.GenreDistribution,
            FavoriteCount = p.FavoriteCount,
            AverageCommunityRating = p.AverageCommunityRating,
            WatchedItems = []
        }).ToList();

        return Ok(lean);
    }

    /// <summary>
    ///     Creates a trimmed copy of each user's recommendation list without mutating the cache.
    /// </summary>
    /// <param name="results">The full recommendation results (not modified).</param>
    /// <param name="maxPerUser">Maximum recommendations per user.</param>
    /// <returns>A new collection with trimmed recommendation counts.</returns>
    private static IReadOnlyList<RecommendationResult> TrimRecommendations(IReadOnlyList<RecommendationResult> results, int maxPerUser)
    {
        var needsTrim = results.Any(r => r.Recommendations.Count > maxPerUser);
        if (!needsTrim)
        {
            return results;
        }

        var trimmed = new List<RecommendationResult>();
        foreach (var r in results)
        {
            if (r.Recommendations.Count > maxPerUser)
            {
                trimmed.Add(new RecommendationResult
                {
                    UserId = r.UserId,
                    UserName = r.UserName,
                    Profile = r.Profile,
                    ScoringStrategy = r.ScoringStrategy,
                    ScoringStrategyKey = r.ScoringStrategyKey,
                    GeneratedAt = r.GeneratedAt,
                    Recommendations = new Collection<RecommendedItem>(
                        r.Recommendations.Take(maxPerUser).ToList())
                });
            }
            else
            {
                trimmed.Add(r);
            }
        }

        return trimmed;
    }

    /// <summary>
    ///     Checks whether smart recommendations are enabled in the plugin configuration.
    ///     Returns true when the task mode is not <see cref="Configuration.TaskMode.Deactivate" />.
    /// </summary>
    /// <returns>True if enabled (DryRun or Activate), false if deactivated.</returns>
    private bool IsRecommendationsEnabled()
    {
        var config = _configService.GetConfiguration();
        return config.RecommendationsTaskMode != Configuration.TaskMode.Deactivate;
    }
}