using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mime;
using Jellyfin.Plugin.JellyfinHelper.Services.Recommendation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Jellyfin.Plugin.JellyfinHelper.Api;

/// <summary>
///     API controller for smart recommendations and watch history.
///     Serves cached recommendation data generated by the scheduled task,
///     with an option to fetch watch profiles on demand.
/// </summary>
[ApiController]
[Authorize(Policy = "RequiresElevation")]
[Route("JellyfinHelper/Recommendations")]
[Produces(MediaTypeNames.Application.Json)]
public class RecommendationController : ControllerBase
{
    private readonly IRecommendationCacheService _cacheService;
    private readonly IRecommendationEngine _engine;
    private readonly IWatchHistoryService _watchHistoryService;

    /// <summary>
    ///     Initializes a new instance of the <see cref="RecommendationController" /> class.
    /// </summary>
    /// <param name="engine">The recommendation engine.</param>
    /// <param name="cacheService">The recommendation cache service.</param>
    /// <param name="watchHistoryService">The watch history service.</param>
    public RecommendationController(
        IRecommendationEngine engine,
        IRecommendationCacheService cacheService,
        IWatchHistoryService watchHistoryService)
    {
        _engine = engine;
        _cacheService = cacheService;
        _watchHistoryService = watchHistoryService;
    }

    /// <summary>
    ///     Gets cached recommendations for all users (admin overview).
    ///     Returns the latest cached results from the scheduled task.
    ///     If no cache exists, generates fresh recommendations on the fly.
    /// </summary>
    /// <param name="maxPerUser">Maximum recommendations per user (default: 20, max: 100).</param>
    /// <returns>A list of recommendation results, one per user.</returns>
    [HttpGet]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status503ServiceUnavailable)]
    public ActionResult<List<RecommendationResult>> GetAllRecommendations(
        [FromQuery] int maxPerUser = 20)
    {
        if (!IsRecommendationsEnabled())
        {
            return StatusCode(StatusCodes.Status503ServiceUnavailable, "Smart Recommendations are disabled in plugin configuration.");
        }

        maxPerUser = Math.Clamp(maxPerUser, 1, 100);

        var cached = _cacheService.LoadResults();
        if (cached is not null)
        {
            // Cache returns the full result set from the scheduled task;
            // maxPerUser is only applied during on-demand generation below.
            return Ok(cached);
        }

        // No cache available — generate on demand
        var results = _engine.GetAllRecommendations(maxPerUser);
        _cacheService.SaveResults(results);
        return Ok(results);
    }

    /// <summary>
    ///     Gets recommendations for a specific user.
    /// </summary>
    /// <param name="userId">The Jellyfin user ID.</param>
    /// <param name="maxResults">Maximum number of recommendations (default: 20, max: 100).</param>
    /// <returns>The recommendation result for the user.</returns>
    [HttpGet("{userId}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status503ServiceUnavailable)]
    public ActionResult<RecommendationResult> GetUserRecommendations(
        Guid userId,
        [FromQuery] int maxResults = 20)
    {
        if (!IsRecommendationsEnabled())
        {
            return StatusCode(StatusCodes.Status503ServiceUnavailable, "Smart Recommendations are disabled in plugin configuration.");
        }

        maxResults = Math.Clamp(maxResults, 1, 100);

        // Try cache first — cached results contain the full recommendation set
        // from the scheduled task; maxResults is only applied during on-demand generation below.
        var cached = _cacheService.LoadResults();
        var cachedUser = cached?.FirstOrDefault(r => r.UserId == userId);
        if (cachedUser is not null)
        {
            return Ok(cachedUser);
        }

        // Generate on demand
        var result = _engine.GetRecommendations(userId, maxResults);
        if (result is null)
        {
            return NotFound();
        }

        return Ok(result);
    }

    /// <summary>
    ///     Gets the watch profile for a specific user (detailed watch history stats).
    /// </summary>
    /// <param name="userId">The Jellyfin user ID.</param>
    /// <returns>The user's watch profile.</returns>
    [HttpGet("WatchProfile/{userId}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public ActionResult<UserWatchProfile> GetUserWatchProfile(Guid userId)
    {
        var profile = _watchHistoryService.GetUserWatchProfile(userId);
        if (profile is null)
        {
            return NotFound();
        }

        return Ok(profile);
    }

    /// <summary>
    ///     Gets watch profiles for all users (admin overview).
    /// </summary>
    /// <returns>A list of watch profiles, one per user.</returns>
    [HttpGet("WatchProfiles")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status503ServiceUnavailable)]
    public ActionResult<List<UserWatchProfile>> GetAllWatchProfiles()
    {
        if (!IsRecommendationsEnabled())
        {
            return StatusCode(StatusCodes.Status503ServiceUnavailable, "Smart Recommendations are disabled in plugin configuration.");
        }

        var profiles = _watchHistoryService.GetAllUserWatchProfiles();

        // Return lean copies without the full watched items list (never mutate originals)
        var lean = profiles.Select(p => new UserWatchProfile
        {
            UserId = p.UserId,
            UserName = p.UserName,
            WatchedMovieCount = p.WatchedMovieCount,
            WatchedEpisodeCount = p.WatchedEpisodeCount,
            WatchedSeriesCount = p.WatchedSeriesCount,
            TotalWatchTimeTicks = p.TotalWatchTimeTicks,
            LastActivityDate = p.LastActivityDate,
            GenreDistribution = p.GenreDistribution,
            FavoriteCount = p.FavoriteCount,
            AverageCommunityRating = p.AverageCommunityRating,
            WatchedItems = []
        }).ToList();

        return Ok(lean);
    }

    /// <summary>
    ///     Checks whether smart recommendations are enabled in the plugin configuration.
    ///     Returns true when the task mode is not <see cref="Configuration.TaskMode.Deactivate" />.
    /// </summary>
    /// <returns>True if enabled (DryRun or Activate), false if deactivated.</returns>
    private static bool IsRecommendationsEnabled()
    {
        var config = Plugin.Instance?.Configuration;
        return config is null || config.RecommendationsTaskMode != Configuration.TaskMode.Deactivate;
    }
}
