using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net.Mime;
using Jellyfin.Plugin.JellyfinHelper.Configuration;
using Jellyfin.Plugin.JellyfinHelper.Services.Activity;
using Jellyfin.Plugin.JellyfinHelper.Services.ConfigAccess;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Jellyfin.Plugin.JellyfinHelper.Api;

/// <summary>
///     API controller for user watch activity insights.
///     Serves cached activity data generated by the scheduled task.
///     Activity data shows which users watched what, when, and how often.
/// </summary>
[ApiController]
[Authorize(Policy = "RequiresElevation")]
[Route("JellyfinHelper/UserActivity")]
[Produces(MediaTypeNames.Application.Json)]
public class UserActivityController : ControllerBase
{
    private readonly IUserActivityCacheService _cacheService;
    private readonly IPluginConfigurationService _configService;
    private readonly IUserActivityInsightsService _insightsService;

    /// <summary>
    ///     Initializes a new instance of the <see cref="UserActivityController" /> class.
    /// </summary>
    /// <param name="cacheService">The user activity cache service.</param>
    /// <param name="insightsService">The user activity insights service.</param>
    /// <param name="configService">The plugin configuration service.</param>
    public UserActivityController(
        IUserActivityCacheService cacheService,
        IUserActivityInsightsService insightsService,
        IPluginConfigurationService configService)
    {
        _cacheService = cacheService;
        _insightsService = insightsService;
        _configService = configService;
    }

    /// <summary>
    ///     Gets the latest cached user activity report.
    ///     Returns the full report with per-item/per-user breakdowns.
    ///     If no cache exists, generates a fresh report on the fly.
    ///     Only available when Recommendations TaskMode is not Deactivate.
    /// </summary>
    /// <returns>The user activity result.</returns>
    [HttpGet("Latest")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status503ServiceUnavailable)]
    public ActionResult<UserActivityResult> GetLatestActivity()
    {
        if (!IsFeatureEnabled())
        {
            return StatusCode(StatusCodes.Status503ServiceUnavailable, "User Activity insights are disabled in plugin configuration.");
        }

        var cached = _cacheService.LoadResult();
        if (cached is not null)
        {
            return Ok(cached);
        }

        // No cache yet — generate on demand
        var config = _configService.GetConfiguration();
        var result = _insightsService.BuildActivityReport();

        // Only persist to cache when TaskMode is Activate (not DryRun)
        if (config.RecommendationsTaskMode == TaskMode.Activate)
        {
            _cacheService.SaveResult(result);
        }

        return Ok(result);
    }

    /// <summary>
    ///     Gets activity data filtered for a specific user.
    ///     Returns only items where the specified user has activity.
    ///     Aggregate fields are recalculated from the filtered user's activities only.
    ///     Only available when Recommendations TaskMode is not Deactivate.
    /// </summary>
    /// <param name="userId">The Jellyfin user ID to filter by.</param>
    /// <param name="maxResults">Maximum number of results to return (1–200, default 15).</param>
    /// <returns>Activity summaries containing only the specified user's data.</returns>
    [HttpGet("User/{userId}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status503ServiceUnavailable)]
    public ActionResult<List<UserActivitySummary>> GetUserActivity(Guid userId, [FromQuery] int maxResults = 15)
    {
        if (!IsFeatureEnabled())
        {
            return StatusCode(StatusCodes.Status503ServiceUnavailable, "User Activity insights are disabled in plugin configuration.");
        }

        if (userId == Guid.Empty)
        {
            return BadRequest("A valid, non-empty userId is required.");
        }

        maxResults = Math.Clamp(maxResults, 1, 200);

        var cached = _cacheService.LoadResult();
        var source = cached ?? _insightsService.BuildActivityReport();

        if (cached is null)
        {
            var config = _configService.GetConfiguration();
            // Only persist to cache when TaskMode is Activate (not DryRun)
            if (config.RecommendationsTaskMode == TaskMode.Activate)
            {
                _cacheService.SaveResult(source);
            }
        }

        // Filter to items where this user has activity, recalculating aggregate fields
        var userItems = source.Items
            .Where(s => s.UserActivities.Any(a => a.UserId == userId))
            .Select(s =>
            {
                var filteredActivities = s.UserActivities
                    .Where(a => a.UserId == userId)
                    .ToList();

                return new UserActivitySummary
                {
                    ItemId = s.ItemId,
                    ItemName = s.ItemName,
                    ItemType = s.ItemType,
                    SeriesName = s.SeriesName,
                    EpisodeLabel = s.EpisodeLabel,
                    Year = s.Year,
                    Genres = s.Genres,
                    CommunityRating = s.CommunityRating,
                    RuntimeTicks = s.RuntimeTicks,
                    TotalPlayCount = filteredActivities.Sum(a => a.PlayCount),
                    UniqueViewers = filteredActivities.Count,
                    MostRecentWatch = filteredActivities
                        .Where(a => a.LastPlayedDate.HasValue)
                        .Select(a => a.LastPlayedDate)
                        .DefaultIfEmpty(null)
                        .Max(),
                    AverageCompletionPercent = filteredActivities.Count > 0
                        ? Math.Round(filteredActivities.Average(a => a.CompletionPercent), 1)
                        : 0,
                    FavoriteCount = filteredActivities.Count(a => a.IsFavorite),
                    UserActivities = new Collection<UserItemActivity>(filteredActivities)
                };
            })
            .OrderByDescending(s => s.MostRecentWatch)
            .Take(maxResults)
            .ToList();

        if (userItems.Count == 0)
        {
            return NotFound();
        }

        return Ok(userItems);
    }

    /// <summary>
    ///     Checks whether user activity insights are enabled in the plugin configuration.
    ///     Returns true when the Recommendations task mode is not <see cref="TaskMode.Deactivate" />.
    /// </summary>
    /// <returns>True if enabled (DryRun or Activate), false if deactivated.</returns>
    private bool IsFeatureEnabled()
    {
        var config = _configService.GetConfiguration();
        return config.RecommendationsTaskMode != TaskMode.Deactivate;
    }
}