using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net.Mime;
using System.Threading;
using System.Threading.Tasks;
using Jellyfin.Plugin.JellyfinHelper.Configuration;
using Jellyfin.Plugin.JellyfinHelper.Services.Activity;
using Jellyfin.Plugin.JellyfinHelper.Services.ConfigAccess;
using MediaBrowser.Controller.Library;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Jellyfin.Plugin.JellyfinHelper.Api;

/// <summary>
///     API controller for user watch activity insights.
///     Serves cached activity data generated by the scheduled task.
///     Activity data shows which users watched what, when, and how often.
/// </summary>
[ApiController]
[Authorize(Policy = "RequiresElevation")]
[Route("JellyfinHelper/UserActivity")]
[Produces(MediaTypeNames.Application.Json)]
[ProducesResponseType(StatusCodes.Status401Unauthorized)]
[ProducesResponseType(StatusCodes.Status403Forbidden)]
public class UserActivityController : ControllerBase, IDisposable
{
    private static readonly SemaphoreSlim _buildLock = new(1, 1);
    private readonly IUserActivityCacheService _cacheService;
    private readonly IPluginConfigurationService _configService;
    private readonly IUserManager _userManager;
    private bool _disposed;

    /// <summary>
    ///     Initializes a new instance of the <see cref="UserActivityController" /> class.
    /// </summary>
    /// <param name="cacheService">The user activity cache service.</param>
    /// <param name="configService">The plugin configuration service.</param>
    /// <param name="userManager">The user manager.</param>
    public UserActivityController(
        IUserActivityCacheService cacheService,
        IPluginConfigurationService configService,
        IUserManager userManager)
    {
        _cacheService = cacheService;
        _configService = configService;
        _userManager = userManager;
    }

    /// <summary>
    ///     Gets the latest cached user activity report.
    ///     Returns the full report with per-item/per-user breakdowns.
    ///     Cache is populated by the scheduled task; returns 503 when no cache is available.
    ///     Only available when Recommendations TaskMode is not Deactivate.
    /// </summary>
    /// <returns>The user activity result.</returns>
    /// <param name="cancellationToken">Cancellation token.</param>
    [HttpGet("Latest")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status503ServiceUnavailable)]
    public async Task<ActionResult<UserActivityResult>> GetLatestActivity(CancellationToken cancellationToken)
    {
        if (!IsFeatureEnabled())
        {
            return StatusCode(StatusCodes.Status503ServiceUnavailable, "User activity feature is disabled in plugin configuration.");
        }

        await _buildLock.WaitAsync(cancellationToken).ConfigureAwait(false);
        try
        {
            var cached = _cacheService.LoadResult();
            if (cached == null)
            {
                return StatusCode(StatusCodes.Status503ServiceUnavailable, "Activity report cache is not yet available. Run the scheduled task to populate it.");
            }

            return Ok(cached);
        }
        finally
        {
            _buildLock.Release();
        }
    }

    /// <summary>
    ///     Gets activity data filtered for a specific user.
    ///     Returns only items where the specified user has activity.
    ///     Aggregate fields are recalculated from the filtered user's activities only.
    ///     Cache is populated by the scheduled task; returns 503 when no cache is available.
    ///     Only available when Recommendations TaskMode is not Deactivate.
    /// </summary>
    /// <param name="userId">The Jellyfin user ID to filter by.</param>
    /// <param name="maxResults">Maximum number of results to return (1–200, default 15).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Activity summaries containing only the specified user's data.</returns>
    [HttpGet("User/{userId}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status503ServiceUnavailable)]
    public async Task<ActionResult<List<UserActivitySummary>>> GetUserActivity(Guid userId, [FromQuery] int maxResults = 15, CancellationToken cancellationToken = default)
    {
        if (!IsFeatureEnabled())
        {
            return StatusCode(StatusCodes.Status503ServiceUnavailable, "User activity feature is disabled in plugin configuration.");
        }

        if (userId == Guid.Empty)
        {
            return BadRequest("A valid, non-empty userId is required.");
        }

        var user = _userManager.GetUserById(userId);
        if (user == null)
        {
            return NotFound();
        }

        maxResults = Math.Clamp(maxResults, 1, 200);

        UserActivityResult source;
        await _buildLock.WaitAsync(cancellationToken).ConfigureAwait(false);
        try
        {
            var cached = _cacheService.LoadResult();
            if (cached == null)
            {
                return StatusCode(StatusCodes.Status503ServiceUnavailable, "Activity report cache is not yet available. Run the scheduled task to populate it.");
            }

            source = cached;
        }
        finally
        {
            _buildLock.Release();
        }

        // Filter to items where this user has activity, recalculating aggregate fields
        var userItems = source.Items
            .Where(s => s.UserActivities.Any(a => a.UserId == userId))
            .Select(s =>
            {
                var filteredActivities = s.UserActivities
                    .Where(a => a.UserId == userId)
                    .ToList();

                // Separate playback-only activities for viewer/completion metrics
                // to avoid counting favorite-only rows as watchers.
                var playbackActivities = filteredActivities
                    .Where(a => a.Played || a.PlayCount > 0 || a.PlaybackPositionTicks > 0)
                    .ToList();

                return new UserActivitySummary
                {
                    ItemId = s.ItemId,
                    ItemName = s.ItemName,
                    ItemType = s.ItemType,
                    SeriesName = s.SeriesName,
                    EpisodeLabel = s.EpisodeLabel,
                    Year = s.Year,
                    Genres = s.Genres,
                    CommunityRating = s.CommunityRating,
                    RuntimeTicks = s.RuntimeTicks,
                    TotalPlayCount = filteredActivities.Sum(a => a.PlayCount),

                    // Per-user context: effectively 0 or 1 since playbackActivities
                    // only contains entries for the single requested user with actual playback.
                    UniqueViewers = playbackActivities.Count > 0 ? 1 : 0,

                    MostRecentWatch = playbackActivities
                        .Where(a => a.LastPlayedDate.HasValue)
                        .Select(a => a.LastPlayedDate)
                        .DefaultIfEmpty(null)
                        .Max(),
                    AverageCompletionPercent = playbackActivities.Count > 0
                        ? Math.Round(playbackActivities.Average(a => a.CompletionPercent), 1)
                        : 0,
                    FavoriteCount = filteredActivities.Count(a => a.IsFavorite),
                    UserActivities = new Collection<UserItemActivity>(filteredActivities)
                };
            })
            .OrderByDescending(s => s.MostRecentWatch)
            .Take(maxResults)
            .ToList();

        // Return 200 OK with empty list when user has no activity.
        return Ok(userItems);
    }

    /// <summary>
    ///     Checks whether user activity insights are enabled in the plugin configuration.
    ///     Returns true when the Recommendations task mode is not <see cref="TaskMode.Deactivate" />.
    /// </summary>
    /// <returns>True if enabled (DryRun or Activate), false if deactivated.</returns>
    private bool IsFeatureEnabled()
    {
        var config = _configService.GetConfiguration();
        return config.RecommendationsTaskMode != TaskMode.Deactivate;
    }

    /// <inheritdoc />
    public void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }

    /// <summary>
    ///     Releases managed resources.
    /// </summary>
    /// <param name="disposing">True when called from <see cref="Dispose()"/>; false when called from a finalizer.</param>
    protected virtual void Dispose(bool disposing)
    {
        if (_disposed)
        {
            return;
        }

        if (disposing)
        {
            // _buildLock is static and must not be disposed per-instance
        }

        _disposed = true;
    }
}