// ESLint flat config for the plugin configuration-page scripts.
//
// All modules in this directory are concatenated into a SINGLE IIFE at build time by
// BuildTasks/ComposeConfigPage.cs, so every top-level function/var lives in one shared
// scope at runtime. ESLint, however, lints each file in isolation. To make no-undef and
// no-unused-vars honest under that model, the cross-module top-level symbols are declared
// here as shared globals: a symbol defined in one module and used in another is neither
// "undefined" at the use site nor "unused" at the definition site.
//
// Keep this list in sync when adding or removing a shared top-level declaration. Symbols
// that are private to a single module do NOT belong here.

'use strict';

// Host-provided global (Jellyfin web client). Not declared in any module.
const hostGlobals = {
    ApiClient: 'readonly',
};

// Browser and DOM globals actually referenced by the scripts.
const browserGlobals = {
    window: 'readonly',
    document: 'readonly',
    console: 'readonly',
    navigator: 'readonly',
    localStorage: 'readonly',
    fetch: 'readonly',
    Blob: 'readonly',
    URL: 'readonly',
    Event: 'readonly',
    CustomEvent: 'readonly',
    FileReader: 'readonly',
    AbortController: 'readonly',
    getComputedStyle: 'readonly',
    requestAnimationFrame: 'readonly',
    cancelAnimationFrame: 'readonly',
    setTimeout: 'readonly',
    clearTimeout: 'readonly',
    setInterval: 'readonly',
    clearInterval: 'readonly',
};

// Top-level symbols shared across the concatenated IIFE scope. Grouped by defining module
// for readability; ESLint treats the whole set as one shared scope, matching runtime.
const sharedModuleGlobals = {
    // Shared.js
    DONUT_COLORS: 'writable',
    _forceScrollOnPanelOpen: 'writable',
    _mi: 'writable',
    mi: 'writable',
    SVG: 'writable',
    getCssVar: 'writable',
    getScoreThresholdClass: 'writable',
    _translations: 'writable',
    T: 'writable',
    loadTranslations: 'writable',
    applyStaticTranslations: 'writable',
    formatBytes: 'writable',
    escAttr: 'writable',
    escHtml: 'writable',
    allowSafeHtml: 'writable',
    getPathSegments: 'writable',
    normalizeStatisticsLibraries: 'writable',
    buildPathTree: 'writable',
    countTreeItems: 'writable',
    FILE_TREE_EXPAND_BUDGET: 'writable',
    renderTreeLevel: 'writable',
    renderTreeFolder: 'writable',
    renderTreeLeaf: 'writable',
    renderFileTreeSection: 'writable',
    renderFileTree: 'writable',
    bindFileTreeHandlers: 'writable',
    toggleTreeNode: 'writable',
    collapseAllTreeNodes: 'writable',
    expandOneTreeNode: 'writable',
    runTreeAction: 'writable',
    aggregateDict: 'writable',
    showAutoSaveIndicatorOverlay: 'writable',
    removeExistingSaveIndicatorOverlay: 'writable',
    createSaveIndicator: 'writable',
    addFadingDelay: 'writable',
    calculateFadeDelay: 'writable',
    showButtonFeedback: 'writable',
    describeApiError: 'writable',
    _apiDefaultError: 'writable',
    apiGet: 'writable',
    apiPost: 'writable',
    apiPut: 'writable',
    apiDelete: 'writable',
    apiGetText: 'writable',
    apiPostRaw: 'writable',
    apiGetOptional: 'writable',
    apiFetchBlob: 'writable',
    pluralize: 'writable',
    formatTimeAgo: 'writable',
    collectFlatPaths: 'writable',
    collectDictPaths: 'writable',
    createDialogOverlay: 'writable',
    createDialogBtn: 'writable',
    removeDialogById: 'writable',
    attachTogglePanelHandlers: 'writable',
    resolveArrInstances: 'writable',

    // Overview.js
    getCollectionBadge: 'writable',
    buildBarSegments: 'writable',
    loadCleanupStats: 'writable',
    fillOverviewData: 'writable',

        // Codecs.js
    _lastCodecData: 'writable',    _donutTooltipData: 'writable',
    toggleCodecBreakdown: 'writable',
    syncCollapsedBreakdownRows: 'writable',
    _codecRowSyncBound: 'writable',
    _activeTooltipSegmentId: 'writable',
    _touchOutsideListenerAttached: 'writable',
    _lastTouchEndTime: 'writable',
    showDonutTooltip: 'writable',
    hideDonutTooltip: 'writable',
    triggerCodecRowForSegment: 'writable',
    polarToCartesian: 'writable',
    describeArc: 'writable',
    renderDonutSvg: 'writable',
    renderCodecBreakdown: 'writable',
    renderDonutChart: 'writable',
    countWatchedUsers: 'writable',
    collectCodecPaths: 'writable',
    collectResolutionDimensions: 'writable',
    collectTrackLabelMeta: 'writable',
    collectDrilldownMeta: 'writable',
    CODEC_PATH_MAP: 'writable',
    CODEC_CATEGORY_MAP: 'writable',
    attachCodecClickHandlers: 'writable',
    attachDonutHoverTooltips: 'writable',
    fillCodecsData: 'writable',

    // CodecsExplorer.js
    _codecsExplorerState: 'writable',
    _codecMultiOpen: 'writable',
    _codecFilterOpen: 'writable',
    _explorerRefreshTimer: 'writable',
    _explorerPreviewTimer: 'writable',
    _explorerSubsetCache: 'writable',
    _explorerMapCache: 'writable',
    _explorerDimIndexCache: 'writable',
    _explorerDetailCache: 'writable',
    _codecExploreLinkBound: 'writable',
    prepareExplorerLeaf: 'writable',
    CODEC_EXPLORER_TYPE_MOVIES: 'writable',
    CODEC_EXPLORER_TYPE_TVSHOWS: 'writable',
    CODEC_EXPLORER_TYPE_MUSIC: 'writable',
    CODEC_EXPLORER_TYPE_BOOKS: 'writable',
    CODEC_EXPLORER_TYPE_GROUPS: 'writable',
    CODEC_EXPLORER_DIMENSIONS: 'writable',
    CODEC_BITRATE_DIM: 'writable',
    CODEC_BITRATE_HISTOGRAM_BIN: 'writable',
    getCodecsExplorerState: 'writable',
    getCodecsExplorerDimension: 'writable',
    getCodecsExplorerLibraries: 'writable',
    getCodecsExplorerGroupLibraries: 'writable',
    getCodecsExplorerSelectedRoots: 'writable',
    codecExplorerIsWindowsPath: 'writable',
    codecExplorerTrimRoot: 'writable',
    codecExplorerPathInRoots: 'writable',
    getCodecsExplorerScopedLibraries: 'writable',
    getExplorerUniverse: 'writable',
    countWatchedUniverse: 'writable',
    getBitrateMap: 'writable',
    getBitrateBounds: 'writable',
    hasActiveBitrateRange: 'writable',
    applyBitrateRange: 'writable',
    getBitrateHistogram: 'writable',
    getExplorerFileBitrate: 'writable',
    getTrackLabelMap: 'writable',
    getExplorerFileTrackLabels: 'writable',
    formatBitrateRange: 'writable',
    normalizeBitrateRange: 'writable',
    explorerMapCacheKey: 'writable',
    getCachedExplorerMaps: 'writable',
    getDimPathIndex: 'writable',
    buildDimPathIndex: 'writable',
    getCodecsExplorerSelection: 'writable',
    isCodecsExplorerExcluded: 'writable',
    getCodecsExplorerActiveDims: 'writable',
    getExplorerCategories: 'writable',
    collectExplorerValuePaths: 'writable',
    unionExplorerPaths: 'writable',
    collectUniversePaths: 'writable',
    intersectPathMaps: 'writable',
    intersectExplorerFilters: 'writable',
    scopeExplorerPaths: 'writable',
    computePathsExcluding: 'writable',
    computeCodecsExplorerPaths: 'writable',
    baseExplorerPaths: 'writable',
    hasOtherActiveFilters: 'writable',
    countExplorerOptions: 'writable',
    countRemainingInUniverse: 'writable',
    countAgainstSubset: 'writable',
    visibleExplorerOptions: 'writable',
    hasVisibleExplorerOptions: 'writable',
    buildCodecsExplorerSingleList: 'writable',
    explorerMultiSummary: 'writable',
    explorerDimSummary: 'writable',
    buildExcludeToggle: 'writable',
    buildCodecsExplorerMulti: 'writable',
    countLibraryFiles: 'writable',
    buildCodecsExplorerLibraryMulti: 'writable',
    libraryMultiSummary: 'writable',
    buildCodecsExplorerControls: 'writable',
    buildCodecsExplorerFilterAdd: 'writable',
    buildCodecsExplorerDimList: 'writable',
    buildCodecsExplorerDimEditor: 'writable',
    buildCodecsExplorerPills: 'writable',
    buildCodecsExplorerPillsInner: 'writable',
    buildBitrateEditor: 'writable',
    readBitrateEditor: 'writable',
    previewBitrateRange: 'writable',
    previewBitrateRangeCoalesced: 'writable',
    commitBitrateRange: 'writable',
    commitBitrateOnEnter: 'writable',
    bindBitrateEditorHandlers: 'writable',
    buildCodecsExplorerHtml: 'writable',
    explorerSummaryLabels: 'writable',
    groupExplorerResults: 'writable',
    collectScopePaths: 'writable',
    findExplorerDimValue: 'writable',
    findExplorerDimValues: 'writable',
    getExplorerFileSize: 'writable',
    getExplorerWatchers: 'writable',
    explorerDetailRow: 'writable',
    explorerWatchedDetail: 'writable',
    buildExplorerFileDetail: 'writable',
    toggleExplorerFileDetail: 'writable',
    bindExplorerFileDetails: 'writable',
    runCodecsExplorerSearch: 'writable',
    describeActiveExplorerControl: 'writable',
    restoreExplorerFocus: 'writable',
    restoreFilterFocus: 'writable',
    findExplorerFocusTarget: 'writable',
    findExplorerFocusBox: 'writable',
    refreshCodecsExplorerControls: 'writable',
    refreshCodecsExplorerControlsDebounced: 'writable',
    onExplorerLibrariesChanged: 'writable',
    onExplorerSingleChanged: 'writable',
    onExplorerMultiChanged: 'writable',
    onExplorerExcludeChanged: 'writable',
    bindCodecsExplorerFilterHandlers: 'writable',
    bindPillHandlers: 'writable',
    setMultiPanelOpen: 'writable',
    closeExplorerMultis: 'writable',
    closeFilterPop: 'writable',
    bindCodecsExplorerControlHandlers: 'writable',
    attachCodecsExplorerHandlers: 'writable',
    pruneCodecsExplorerState: 'writable',
    pruneExplorerScopeNames: 'writable',
    pruneExplorerDimSelection: 'writable',
    pruneBitrateRange: 'writable',
    resolveExplorerScope: 'writable',
    openCodecsExplorer: 'writable',
    renderCodecsExplorer: 'writable',

    // Health.js
    _lastScanResult: 'writable',
    collectHealthPaths: 'writable',
    renderHealthChecks: 'writable',
    HEALTH_PATH_MAP: 'writable',
    attachHealthClickHandlers: 'writable',
    _trashHealthRequestId: 'writable',
    loadTrashHealthSection: 'writable',
    fillHealthData: 'writable',

    // Trends.js
    formatGranularityLabel: 'writable',
    interpolateDataPoints: 'writable',
    advanceBucketDate: 'writable',
    renderTrendChart: 'writable',
    attachTrendInteraction: 'writable',
    _insightsLoadSeq: 'writable',
    loadInsightsData: 'writable',
    renderInsightCards: 'writable',
    toggleInsightPanel: 'writable',
    buildLargestTree: 'writable',
    buildRecentTree: 'writable',
    insightLibrarySortOrder: 'writable',
    groupByLibrary: 'writable',
    getInsightTypeBadge: 'writable',
    formatInsightDate: 'writable',
    _trendLoadRequestSeq: 'writable',
    loadTrendData: 'writable',

    // Settings.js
    _currentLang: 'writable',
    _wasTrashEnabled: 'writable',
    _previousTrashPath: 'writable',
    _trashPathChangeHandled: 'writable',
    _currentLogLevel: 'writable',
    _logLevelLoaded: 'writable',
    isSeerrConfigured: 'writable',
    refreshDiscoveryAccessState: 'writable',
    updateRecsTabVisibility: 'writable',
    updateSeerrUIState: 'writable',
    _settingsSnapshot: 'writable',
    _settingsInteracted: 'writable',
    _settingsSavedHideTimer: 'writable',
    _saveBandRevealTimer: 'writable',
    _saveBandSaving: 'writable',
    takeSettingsSnapshot: 'writable',
    hasUnsavedSettings: 'writable',
    getSaveBand: 'writable',
    cancelSaveBandReveal: 'writable',
    _saveBandHiddenCleanupTimer: 'writable',
    _saveBandHideDurationMs: 'writable',
    cancelSaveBandHiddenCleanup: 'writable',
    renderSaveBand: 'writable',
    refreshSaveBand: 'writable',
    _dirtyDebounceTimer: 'writable',
    _dirtyTrackingController: 'writable',
    _dirtyTrackingHandler: 'writable',
    _dirtyTrackingForm: 'writable',
    handleDirtyInput: 'writable',
    attachDirtyTracking: 'writable',
    checkUnsavedAndProceed: 'writable',
    renderArrCollapseButton: 'writable',
    rebuildUI: 'writable',
    loadSettings: 'writable',
    buildSettingsPayload: 'writable',
    doSaveSettings: 'writable',
    postSettingsPayload: 'writable',
    buildSaveErrorLabel: 'writable',
    probeBackendReachability: 'writable',
    removeTrashDialog: 'writable',
    formatPathList: 'writable',
    showTrashDisableDialog: 'writable',
    showTrashDeleteConfirmation: 'writable',
    attachBackupHandlers: 'writable',
    triggerBackupExport: 'writable',
    triggerBackupImport: 'writable',
    showBackupImportConfirmation: 'writable',
    removeBackupDialog: 'writable',
    doBackupImport: 'writable',
    attachSeerrHandlers: 'writable',
    attachDiscoveryCopyHandler: 'writable',
    fallbackCopy: 'writable',
    attachAutoSaveHandlers: 'writable',
    showInlineCheckboxIndicator: 'writable',
    showLibraryMultiSelectIndicator: 'writable',
    initLibraryMultiSelects: 'writable',
    parseCommaSeparatedSet: 'writable',
    renderLibraryMultiSelect: 'writable',
    toggleLibraryDropdown: 'writable',
    updateLibraryMultiSelectSummary: 'writable',
    getLibraryMultiSelectValue: 'writable',
    libraryMultiSelectEmptyLabel: 'writable',
    seedArrLibraryInitialValues: 'writable',
    renderArrLibraryMultiSelects: 'writable',
    filterLibrariesForArrType: 'writable',
    renderArrLibraryFallbacks: 'writable',
    attachOrphanAgeInputHandler: 'writable',
    attachTrashPathInputHandler: 'writable',
    attachTrashDaysInputHandler: 'writable',
    SENSITIVE_SYSTEM_ROOTS: 'writable',
    isSensitiveSystemPath: 'writable',
    validateTrashPath: 'writable',
    showTrashPathError: 'writable',
    hasTrashPathChanged: 'writable',
    showTrashPathChangeDialog: 'writable',
    saveSettings: 'writable',

    // ArrIntegration.js
    MAX_ARR_INSTANCES: 'writable',
    _testTimers: 'writable',
    renderArrInstances: 'writable',
    renderArrInstanceRow: 'writable',
    setArrInstanceApiKeys: 'writable',
    collectArrInstances: 'writable',
    updateArrCollapsibleCount: 'writable',
    createArrCountText: 'writable',
    addArrInstance: 'writable',
    removeArrInstance: 'writable',
    syncArrLibraryPickers: 'writable',
    testArrConnection: 'writable',
    attachTestHandlers: 'writable',
    attachRemoveHandlers: 'writable',
    attachAddHandlers: 'writable',
    _arrInstancesCache: 'writable',
    _arrStatusCache: 'writable',
    _arrStatusTtlMs: 'writable',
    _arrStatusReqSeq: 'writable',
    _arrCacheKey: 'writable',
    _renderArrStatusBadge: 'writable',
    refreshArrInstanceStatus: 'writable',
    _renderArrTypeBlock: 'writable',
    initArrButtons: 'writable',
    _wireArrCompareControls: 'writable',
    renderArrSection: 'writable',
    compareArr: 'writable',

    // Recommendations.js
    MAX_ACTIVITY_ROWS: 'writable',
    _profileReqId: 'writable',
    _activityReqId: 'writable',
    _recsListReqId: 'writable',
    _recsResults: 'writable',
    _recsTimestamp: 'writable',
    _seerrServicesCache: 'writable',
    initRecommendationsTab: 'writable',
    loadRecommendations: 'writable',
    renderRecommendations: 'writable',
    onUserChanged: 'writable',
    toggleCollapsible: 'writable',
    _ensembleDiagCache: 'writable',
    loadEnsembleDiagnostics: 'writable',
    renderEnsembleDiagnostics: 'writable',
    renderUserRecommendations: 'writable',
    renderRecommendationCard: 'writable',
    loadUserWatchProfile: 'writable',
    renderCompactWatchProfile: 'writable',
    loadUserActivity: 'writable',
    renderCompactActivityTable: 'writable',
    getTopGenresFromDistribution: 'writable',
    _discoveryReqId: 'writable',
    renderDiscoverySection: 'writable',
    _discoveryAllUsersCache: 'writable',
    _discoveryAllUsersCacheTimestamp: 'writable',
    _discoveryCacheTtlMs: 'writable',
    loadDiscoveryForUser: 'writable',
    findUserDiscovery: 'writable',
    renderDiscoveryCards: 'writable',
    renderDiscoveryCard: 'writable',
    handleDiscoveryRequest: 'writable',
    _seerrServicesCacheTtlMs: 'writable',
    showSeerrUserPopup: 'writable',
    renderQualityProfilePopup: 'writable',
    handleDiscoveryRequestResponse: 'writable',
    handleDiscoveryRequestError: 'writable',
    submitDiscoveryRequestWithProfile: 'writable',
    submitDiscoveryRequest: 'writable',
    markDiscoveryItemRequested: 'writable',

    // Logs.js
    _logsAutoRefreshTimer: 'writable',
    _logsAutoRefreshEnabled: 'writable',
    _logsLoadSeq: 'writable',
    _logsTabInitialized: 'writable',
    _logsInitSeq: 'writable',
    _logsSourceDebounceTimer: 'writable',
    renderLogsTab: 'writable',
    initLogsTab: 'writable',
    loadLogLevelFromConfig: 'writable',
    saveLogLevelToConfig: 'writable',
    destroyLogsTab: 'writable',
    resetLogsTabState: 'writable',
    startLogsAutoRefresh: 'writable',
    stopLogsAutoRefresh: 'writable',
    loadLogs: 'writable',
    downloadLogs: 'writable',
    clearLogs: 'writable',
    formatLogTimestamp: 'writable',

    // FolderBrowser.js
    closeDialog: 'writable',
    initFolderBrowser: 'writable',
    openFolderBrowserDialog: 'writable',
    loadLibraryPathsForBrowser: 'writable',
    browseTo: 'writable',

    // Main.js
    initTabs: 'writable',
    doTabSwitch: 'writable',
    updateLastScanBadge: 'writable',
    loadLatestStatistics: 'writable',
    renderShell: 'writable',
    fillScanData: 'writable',
    _maxInitRetries: 'writable',
    loadStatistics: 'writable',
    initPage: 'writable',
    bindPageLifecycle: 'writable',
};

module.exports = [
    {
        files: ['**/*.js'],
        ignores: ['eslint.config.js'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'script',
            globals: {
                ...browserGlobals,
                ...hostGlobals,
                ...sharedModuleGlobals,
            },
        },
        rules: {
            'no-undef': 'error',
            // vars:'local' scopes the check to function-local declarations: real dead locals
            // are caught, while top-level declarations (globals in the shared IIFE scope, used
            // cross-module) are not falsely flagged. args:'none' ignores unused parameters that
            // exist only to match a callback signature.
            'no-unused-vars': ['error', { vars: 'local', args: 'none' }],
        },
    },
];
